title = Combinatorica
description = A modular Luanti game that unifies popular community mods through a common API, allowing seamless integration and server-customizable gameplay.
allowed_mapgens = v7,carpathian,valleys,flat,fractal,singlenode
default_mapgen = v7
disallowed_mapgen_settings = mgv6_spflags
