name = techage
title = Techage
description = Complete technology mod with electricity, machines, power grid, item transport, and automation.
depends = combinatorica_core, default
optional_depends = farming, moreores, hunger
