name = ethereal
title = Ethereal NG
description = Adds extra biomes with unique trees, plants, and terrain while staying close to vanilla style.
depends = combinatorica_core, default
optional_depends = farming, stairs, walls, doors, dye, bonemeal
