name = everness
title = Everness
description = Diverse surface and underground biomes with structures, dungeons, loot, and custom skyboxes.
depends = combinatorica_core, default
optional_depends = stairs, walls, doors
